os: osx
language: objective-c

# Add new versions to test here
env:
  - NODE=8

before_install:
  - nvm install $NODE
  - nvm use $NODE
  - npm install -g npm
  - npm config set loglevel warn
  - cd server

install:
  - npm install

script:
  - npm test
